linters:
  enable:
    - goimports
  disable:
    - typecheck

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    local-prefixes: github.com/vleukhin/prom-light