version: '3.2'

services:
  postgres:
    image: postgres:10.10
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: praktikum
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data:cached